<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesWithCount()
    {
        return $this->createQueryBuilder('c')
            ->select('c, count(a.id) as countArticles')
            ->leftJoin('c.articles', 'a')
            ->groupBy('c')
            ->getQuery()
            ->getResult();
    }
}
