<?php

namespace AppBundle\Repository;
use AppBundle\Model\PaginatorWithPages;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getRecentComments($page = 1, $max = 5)
    {
        $first = $max * ($page - 1);
        $query = $this->createQueryBuilder('c')
            ->select('c, a, u')
            ->join('c.article', 'a')
            ->join('c.user', 'u')
            ->orderBy('c.createdAt', 'DESC')
            ->setFirstResult($first)
            ->setMaxResults($max)
            ->getQuery();

        return new PaginatorWithPages($query, $fetchJoinCollection = true);
    }

    public function getArticleComment($slug, $page = 1, $max = 5)
    {
        $first = $max * ($page - 1);
        $query = $this->createQueryBuilder('c')
            ->select('c, a, u')
            ->join('c.article', 'a')
            ->where('a.slug = ?1')
            ->join('c.user', 'u')
            ->orderBy('c.createdAt', 'DESC')
            ->setFirstResult($first)
            ->setMaxResults($max)
            ->setParameter(1, $slug)
            ->getQuery();

        return new PaginatorWithPages($query, $fetchJoinCollection = true);
    }

    public function getCountComments()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.id) as countComments')
            ->getQuery()
            ->getSingleResult();
    }
}
