<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getRecentComments($max = 5)
    {
        return $this->createQueryBuilder('c')
            ->select('c, a, u')
            ->join('c.article', 'a')
            ->join('c.user', 'u')
            ->orderBy('c.createdAt', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
    }
}
