<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagsWithCount()
    {
        return $this->createQueryBuilder('t')
            ->select('t, count(a.id) as countArticles')
            ->leftJoin('t.articles', 'a')
            ->groupBy('t')
            ->getQuery()
            ->getResult();
    }
}
